PIP packages
openDAQ/openDAQ pull request #10
Opened 2023-10-18 11:54 UTC by Yarikk26

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Description:

This PR adds PIP packages building functionality

2023-10-23 11:34 UTC, mojca commented
```
>python -m twine upload --repository testpypi opendaq-2.1.0-cp38-cp38-linux_x86_64.whl
Uploading distributions to https://test.pypi.org/legacy/
Enter your username:
Enter your password:
Uploading opendaq-2.1.0-cp38-cp38-linux_x86_64.whl
100% ---------------------------------------- 15.7/15.7 MB • 00:03 • 5.0 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
         Binary wheel 'opendaq-2.1.0-cp38-cp38-linux_x86_64.whl' has an unsupported platform tag 'linux_x86_64'.
```

2023-10-24 10:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openDAQ/openDAQ?pullRequest=10) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/openDAQ/openDAQ?pullRequest=10) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Yarikk26<br/>:x: mojca<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openDAQ/openDAQ?pullRequest=10) it.</sub>

2023-10-24 12:06 UTC, mojca commented
I'm getting
```
Build started...
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>Checking File Globs
2>------ Skipped Build: Project: test_py_opendaq, Configuration: Debug x64 ------
2>Project not selected to build for this solution configuration 
3>------ Build started: Project: py_opendaq_daq, Configuration: Debug x64 ------
3>LINK : fatal error LNK1104: cannot open file 'python311.lib'
3>Done building project "py_opendaq_daq.vcxproj" -- FAILED.
```
when I try to build the package with these changes on my local machine.

2023-10-25 13:56 UTC, Yarikk26 commented
> I'm getting
> 
> ```
> Build started...
> 1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
> 1>Checking File Globs
> 2>------ Skipped Build: Project: test_py_opendaq, Configuration: Debug x64 ------
> 2>Project not selected to build for this solution configuration 
> 3>------ Build started: Project: py_opendaq_daq, Configuration: Debug x64 ------
> 3>LINK : fatal error LNK1104: cannot open file 'python311.lib'
> 3>Done building project "py_opendaq_daq.vcxproj" -- FAILED.
> ```
> 
> when I try to build the package with these changes on my local machine (VS 2022; no special configuration to explicitly declare the desired Python version).

Clean build dir. Just followed instructions to build under Windows:
- `cmake --preset "x64/msvc-22/full"`
- switch OPENDAQ_ENABLE_PYTHON_BINDINGS_TESTS to ON by GUI app without specifying exact version
- ` cmake --build . -t py_opendaq_daq` in `build\x64\msvc-22\full`
Can't reproduce:
```
  py_opendaq.vcxproj -> C:\Users\lenovo\source\repos\openDAQ\openDAQ\build\x64\msvc-22\full\bin\Debug\py_opendaq-debug.
  lib
  Building Custom Rule C:/Users/lenovo/source/repos/openDAQ/openDAQ/bindings/python/py_opendaq_daq/CMakeLists.txt
  opendaq_daq.cpp
     Creating library C:/Users/lenovo/source/repos/openDAQ/openDAQ/build/x64/msvc-22/full/bin/Debug/opendaq.lib and obj
  ect C:/Users/lenovo/source/repos/openDAQ/openDAQ/build/x64/msvc-22/full/bin/Debug/opendaq.exp
  py_opendaq_daq.vcxproj -> C:\Users\lenovo\source\repos\openDAQ\openDAQ\build\x64\msvc-22\full\bin\Debug\opendaq.cp312
  -win_amd64.pyd
```
Could you please provide more debug info? E.g. CMakeCache.txt, CMake output or at least steps to reproduce

2023-10-26 06:06 UTC, JakaMohorkoDS requested changes

2023-10-26 06:06 UTC, JakaMohorkoDS commented on .github/workflows/deploy.yml
> +          aws s3 cp . "s3://${{ env.s3bucket }}/${{ env.s3wheels_win_amd64_path }}" --recursive
This should run only on push to main,

2023-10-26 06:06 UTC, JakaMohorkoDS commented on .github/workflows/deploy.yml
> +          aws s3 cp . "s3://${{ env.s3bucket }}/${{ env.s3wheels_linux_x86_64_path }}" --recursive
As above, should only run on main.

2023-10-26 06:06 UTC, JakaMohorkoDS commented on bindings/python/package/METADATA.in
> +Project-URL: Download, https://docs.opendaq.com/
Can we add a link to the GitHub repo here?

2023-10-26 06:06 UTC, JakaMohorkoDS commented on bindings/python/package/METADATA.in
> +Requires-Python: >=3.7
3.8

2023-10-26 13:02 UTC, JakaMohorkoDS approved these changes
Approved from my side, should also wait for @mojca to review the changes.

2023-10-26 14:27 UTC, mojca commented
Aren't these changes going to the `release/2.0` branch, so that when we release a new patch version, the wheels can easily be generated there?

I'll do some testing now.

2023-10-26 15:17 UTC, mojca reviewed
I would prefer to see the changes that modify the functionality (`CMakeLists.txt`, remove the patch for `pybind11` etc.) separate from CI changes.

It might also be nice to have `bindings/python/package` contents added as a separate commit. So I see at least 3 separate commits in place here.

I would suggest to put the changes into the release rather than the main branch. We will almost certainly want to build some bugfix releases for 2.0.x. If we can only build the wheels in the main branch, making new wheels will be more challenging. Maybe we only want to upload wheels from the main branch to AWS, but that's a different topic/question.

2023-10-26 19:55 UTC, Yarikk26 commented
> Aren't these changes going to the `release/2.0` branch, so that when we release a new patch version, the wheels can easily be generated there?
> 
> I'll do some testing now.

We decide with @JakaMohorkoDS to move to main

2023-10-26 20:26 UTC, Yarikk26 commented
> I would prefer to see the changes that modify the functionality (`CMakeLists.txt`, remove the patch for `pybind11` etc.) separate from CI changes.
> 
> It might also be nice to have `bindings/python/package` contents added as a separate commit. So I see at least 3 separate commits in place here.
> 
> I would suggest to put the changes into the release rather than the main branch. We will almost certainly want to build some bugfix releases for 2.0.x. If we can only build the wheels in the main branch, making new wheels will be more challenging. Maybe we only want to upload wheels from the main branch to AWS, but that's a different topic/question.

I thinks these changes are closely related to each other. If you separate them, you would get half working states. You can't build working Wheels for Linux without CMake changes. You can't also test without CMake changes. Yes, I could separate them but this is eventually extra work just for the same final result.

2023-10-30 07:53 UTC, JakaMohorkoDS commented on .github/workflows/ci.yml
> +  python_versions: 3.8 3.9 3.10 3.11 3.12
Manylinux is fine as it's still faster than the Windows build.

2023-10-30 07:57 UTC, JakaMohorkoDS commented
> Aren't these changes going to the `release/2.0` branch, so that when we release a new patch version, the wheels can easily be generated there?
> 
> I'll do some testing now.

I suppose we could, but the 2.0 branch won't really be maintained/patched, so building new python packages should not be needed. It might be worth merging it to release anyhow though (if so, I apologise for having to swap targets 3 times now)

2023-11-02 10:07 UTC, JakaMohorkoDS commented
I resolved some of the comments, but they should be considered in future PRs once the generation script and CI will be improved.

2023-11-02 10:18 UTC, mojca approved these changes
Apart from me not being able to build this (I have no idea how many other users might potentially be affected), it looks ok.

Some further comments:
* Yes, the split of commits is ok, thank you very much. We could slightly improve the wording to better match "When applied, this commit will <commit message>". For example something similar to "Remove no longer needed patch for pybind11" (optionally a very short explanation), "Support building Python wheel packages", "Build Python wheels as part of CI", ...
* I would still like to see the target to be `release`. If nothing else, we did in fact use these changes to build the packages that we uploaded. And even if this branch won't be maintained, if there is some ugly bug in Python that could easily be fixed, it will remain easy to rebuild the packages. (I don't really care if the CI commit ends up in release, but it would be really nice to have the other two.) If needed, I can take care of rebasing, just let me know.
* There are a few things that could be improved, but they can be improved later. Right now it's significantly better that we are able to build the packages at all, compared to having no binaries available. Even if it' still suboptimal, it can be improved in later commits.

2023-11-02 19:06 UTC, merged