[TBBAS-1162] Python GUI App refactoring
openDAQ/openDAQ pull request #140
Opened 2024-02-13 07:42 UTC by Yarikk26

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] Pull request title reflects its content
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Description:
Python gui_demo app refactoring

2024-02-14 08:13 UTC, dejancrn requested changes

2024-02-14 08:13 UTC, dejancrn commented on examples/python/gui_demo.py
> +        if daq.IDevice.can_cast_from(component):
Folder names at the moment use local ids. For now please check if component is IFolder and if it has the specified local_id, use fixed name:

"Sig": "Signals"
"FB": "Function blocks"
"Dev": "Devices"
"IP": "Input ports"
"IO": "Inputs/Outputs"

2024-02-14 08:13 UTC, dejancrn commented on examples/python/gui_demo.py
> +        if (daq.IFolder.can_cast_from(component)):
Check if component is folder and if it is empty (has no children) do not add it.

2024-02-20 12:34 UTC, JakaMohorkoDS approved these changes
From my perspective this now has the features required. It needs a bit of a usability rework, but it serves its current purpose. We can continue with usability changes in the next iteration.

2024-02-21 10:52 UTC, merged

2024-02-21 10:53 UTC, dejancrn approved these changes