RTGen - Fixed enum value parsing in RTGenListener
openDAQ/openDAQ pull request #27
Opened 2023-11-01 13:01 UTC by Daniel-BB

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] Pull request title reflects its content
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Description:

Previously, an enumeration value got "0x" removed when in Hex and then converted to Integer. The new string was presented to the language where it was hard to determine if it was Hex or Decimal.
In addition, a Decimal value (or Binary value converted to Decimal) would have been converted to Integer using the Hex-Converter resulting in a wrong Decimal value (eg. "12" -> 18).
The fix handles string-conversion correctly and will always return a Decimal value, since the Hex decorator may differ from language to language.

2023-11-02 06:30 UTC, JakaMohorkoDS commented
Shouldn't the RTGen binaries also be committed if the source was changed?

2023-11-02 10:22 UTC, Daniel-BB commented
> Shouldn't the RTGen binaries also be committed if the source was changed?

I totally forgot, added now.

2023-11-07 09:17 UTC, Unsttopabull requested changes

2023-11-07 09:17 UTC, Unsttopabull commented on shared/tools/RTGen/src/project/RTGen.Cpp/Parser/RTGenListener.cs
> +            opt.Value = parsedCounter.ToString(CultureInfo.InvariantCulture);
This overrides the text for binary values (starting with `0b`)

2023-11-07 12:28 UTC, Unsttopabull approved these changes

2023-11-07 15:48 UTC, merged