Retain the original value while converting Ordinal Object to Bool
openDAQ/openDAQ pull request #496
Opened 2024-09-11 08:09 UTC by sedovmo

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] Pull request title reflects its content
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Description:
Assigning the result of getPropertyValue() to `uint8_t can be dangerous, because it implicitly casts to daq::Bool and converts the original value to either 0 or 1.
This is because daq::Bool is uint8_t by definition. During the conversion to Bool, the original value is replaced by daq::True or daq::False.
The suggestion is to keep the original during the conversion.

```cpp
uint8_t value = 33;
objPtr.setPropertyValue("StreamId", value);
uint16_t uint16Val = obj.getPropertyValue("StreamId");
ASSERT_EQ(int16Val, value); // pass
uint8_t uint8Val = obj.getPropertyValue("StreamId");
ASSERT_EQ(int8Val, value); // fail
```

2024-09-11 08:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openDAQ/openDAQ?pullRequest=496) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openDAQ/openDAQ?pullRequest=496) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openDAQ/openDAQ?pullRequest=496) it.</sub>

2024-09-13 07:12 UTC, JakaMohorkoDS approved these changes

2024-09-16 11:21 UTC, dejancrn requested changes
Looks ok, but the test for this would look something like this:

```
TEST_F(IntegerTest, CastUInt8_t)
{
    auto intObj = Integer(2);

    uint8_t valInt = intObj;
    ASSERT_EQ(valInt, 2);
}
```

and it should be part of coretypes tests test_integer.cpp

2024-09-16 13:34 UTC, dejancrn approved these changes

2024-09-18 10:30 UTC, merged